# Site settings
title: petapetapeta
email: poulsen.peterh@gmail.com
description: >
  this is my blog for various things in programming.
baseurl: ""
url: "http://petapetapeta.github.io"
github_username:  petapetapeta
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
